apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-server
  labels:
    app: hello-server
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: hello-server:v1